<?php
declare(strict_types=1);

/**
 * Generates the user-seed SQL from passwords supplied at run time.
 *
 * WHY THIS EXISTS
 *
 * src/sql/004-seed-users.sql and 005-grader-compat.sql used to be tracked with
 * the grader passwords written into their comments and the bcrypt hashes inline.
 * The repository is public, so that published live credentials — including the
 * one that is also the droplet's SSH password. Both files are now gitignored and
 * produced by this script instead, which contains no secrets and is safe to track.
 *
 * Passwords are read from a prompt by default rather than argv, because argv ends
 * up in shell history and in `ps` output on a shared box.
 *
 * Usage:
 *   php make-users.php > ../../sql/004-seed-users.sql        # prompts
 *   php make-users.php --print-only                          # inspect first
 *   php make-users.php --admin=... --basic=... --viewer=... --perf=...   # non-interactive
 *
 * HW5 accounts, one per authorisation level the grader has to see:
 *   grader-admin   super_admin   everything, including user management
 *   grader-basic   analyst       all three sections
 *   grader-perf    analyst       performance section ONLY (the "Sam" case)
 *   grader-viewer  viewer        saved reports only
 * The section rows for the two analysts are written here too, so a fresh
 * database is fully set up by this one file after 007 has been applied.
 *
 * Then apply as usual:
 *   sudo mysql < 004-seed-users.sql
 */

$opt = getopt('', ['admin::', 'basic::', 'viewer::', 'perf::', 'grader::', 'grader-only',
                   'no-grader', 'print-only', 'help']);
$graderOnly = isset($opt['grader-only']);   // emit 005 instead of 004

if (isset($opt['help'])) {
    fwrite(STDERR, "see the header of this file\n");
    exit(0);
}

/** Prompt without echoing, so the password is not left on screen. */
function ask(string $label): string
{
    if (!stream_isatty(STDIN)) {
        fwrite(STDERR, "no TTY: pass --$label=... instead\n");
        exit(1);
    }
    fwrite(STDERR, "$label password: ");
    $useStty = strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN';
    if ($useStty) { shell_exec('stty -echo'); }
    $v = trim((string) fgets(STDIN));
    if ($useStty) { shell_exec('stty echo'); }
    fwrite(STDERR, "\n");
    if ($v === '') { fwrite(STDERR, "empty password refused\n"); exit(1); }
    if (strlen($v) < 8) { fwrite(STDERR, "password must be at least 8 characters\n"); exit(1); }
    return $v;
}

if ($graderOnly) {
    $admin = $basic = null;
    $grader = (string) ($opt['grader'] ?? '') ?: ask('grader (HW3 compat)');
} else {
    $admin  = (string) ($opt['admin'] ?? '') ?: ask('grader-admin');
    $basic  = (string) ($opt['basic'] ?? '') ?: ask('grader-basic');
    $viewer = (string) ($opt['viewer'] ?? '') ?: ask('grader-viewer');
    $perf   = (string) ($opt['perf'] ?? '') ?: ask('grader-perf');
    $grader = null;
}

$h = static fn(string $p): string => password_hash($p, PASSWORD_DEFAULT);

$header = <<<SQL
-- GENERATED by src/tools/seed-users/make-users.php — do not commit.
-- This file is gitignored: it contains real password hashes.
--
-- Regenerate:
--   php src/tools/seed-users/make-users.php > src/sql/004-seed-users.sql
--   php src/tools/seed-users/make-users.php --grader-only > src/sql/005-grader-compat.sql
-- Apply:
--   sudo mysql < ~/cse135/sql/004-seed-users.sql
--
-- Re-running RESETS these passwords to whatever was supplied at generation time.
--
-- BEFORE THIS SITE GOES PUBLIC: delete these accounts.
--   DELETE FROM users WHERE username IN ('grader-admin','grader-basic','grader-perf','grader-viewer','grader');
-- Create a real administrator first — users.php refuses to remove the last one.

USE cse135;

SQL;

if ($graderOnly) {
    // HW3's write-up documents `curl -u grader:...` against /api. Scoped to
    // analyst: HW3 had no user management, so the shim needs no admin rights.
    $out = $header . <<<SQL
INSERT INTO users (username, email, password_hash, role, created_at) VALUES
  ('grader', 'grader@ucsdwrestlingclub.com',
   '{$h($grader)}', 'analyst', UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE
  password_hash = VALUES(password_hash),
  role          = VALUES(role),
  email         = VALUES(email),
  updated_at    = UTC_TIMESTAMP();

SQL;
} else {
    $out = $header . <<<SQL
INSERT INTO users (username, email, password_hash, role, created_at) VALUES
  ('grader-admin', 'grader-admin@ucsdwrestlingclub.com',
   '{$h($admin)}', 'super_admin', UTC_TIMESTAMP()),
  ('grader-basic', 'grader-basic@ucsdwrestlingclub.com',
   '{$h($basic)}', 'analyst', UTC_TIMESTAMP()),
  ('grader-perf', 'grader-perf@ucsdwrestlingclub.com',
   '{$h($perf)}', 'analyst', UTC_TIMESTAMP()),
  ('grader-viewer', 'grader-viewer@ucsdwrestlingclub.com',
   '{$h($viewer)}', 'viewer', UTC_TIMESTAMP())
ON DUPLICATE KEY UPDATE
  password_hash = VALUES(password_hash),
  role          = VALUES(role),
  email         = VALUES(email),
  updated_at    = UTC_TIMESTAMP();

-- Section scoping (HW5, needs 007). Rewritten in full so re-running restores the
-- documented state even if a grader changed it mid-marking.
DELETE us FROM user_sections us
  JOIN users u ON u.id = us.user_id
 WHERE u.username IN ('grader-basic', 'grader-perf');
INSERT INTO user_sections (user_id, section)
SELECT id, s.section FROM users
  JOIN (SELECT 'performance' AS section
        UNION ALL SELECT 'behaviour'
        UNION ALL SELECT 'audience') s
 WHERE username = 'grader-basic';
INSERT INTO user_sections (user_id, section)
SELECT id, 'performance' FROM users WHERE username = 'grader-perf';

SQL;
}

if (isset($opt['print-only'])) {
    fwrite(STDERR, "--- generated SQL (hashes redacted) ---\n");
    echo preg_replace('/\$2y\$[.\/A-Za-z0-9$]+/', '\\$2y\\$<hash>', $out);
    exit(0);
}

echo $out;
fwrite(STDERR, "wrote seed SQL. Remember: the output file is gitignored — keep it that way.\n");
