<?php
/*
 * Shared helpers for the HW2 PHP demos.
 * Not a page — included by the demo scripts. Direct requests get a 403.
 */

if (!defined('HW2_LIB')) {
    if (basename($_SERVER['SCRIPT_FILENAME'] ?? '') === 'lib.php') {
        header('HTTP/1.1 403 Forbidden');
        header('Content-Type: text/plain; charset=utf-8');
        echo "Not a page.\n";
        exit;
    }
}

const LANG_NAME = 'PHP';
const TEAM_NAME = 'Diego — UCSD Wrestling Club';

/** HTML-escape. ENT_QUOTES so the value is safe in attributes too. */
function h(?string $s): string
{
    return htmlspecialchars($s ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

function client_ip(): string
{
    return $_SERVER['REMOTE_ADDR'] ?? 'unknown';
}

function user_agent(): string
{
    return $_SERVER['HTTP_USER_AGENT'] ?? '(none sent)';
}

function server_hostname(): string
{
    return $_SERVER['SERVER_NAME'] ?? php_uname('n');
}

/** ISO-8601 with timezone, so the "generated at" value is unambiguous. */
function now_iso(): string
{
    return (new DateTimeImmutable('now'))->format(DateTimeInterface::ATOM);
}

/**
 * Read and parse the request body.
 *
 * $_POST only populates for POST + x-www-form-urlencoded, so PUT, DELETE and
 * any JSON body have to be read off php://input and parsed by hand.
 *
 * @return array{0: array<string,mixed>, 1: string} [parsed fields, raw body]
 */
function parsed_body(): array
{
    $ct  = $_SERVER['CONTENT_TYPE'] ?? '';
    $raw = file_get_contents('php://input');

    if ($raw === false) {
        $raw = '';
    }

    if (stripos($ct, 'application/json') !== false) {
        $decoded = json_decode($raw, true);
        return [is_array($decoded) ? $decoded : [], $raw];
    }

    // PHP may have already consumed the stream into $_POST.
    if ($raw === '' && !empty($_POST)) {
        return [$_POST, http_build_query($_POST)];
    }

    $fields = [];
    parse_str($raw, $fields);
    return [$fields, $raw];
}

function page_top(string $title): void
{
    header('Content-Type: text/html; charset=utf-8');
    header('Cache-Control: no-store');
    header('X-Content-Type-Options: nosniff');
    ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="stylesheet" href="/css/style.css">
  <link rel="stylesheet" href="/hw2/hw2.css">
  <title><?= h($title) ?></title>
</head>

<body>
  <header>
    <h1><?= h($title) ?></h1>
    <p class="tagline"><span class="lang-badge"><?= h(LANG_NAME) ?></span> <?= h(TEAM_NAME) ?></p>
  </header>

  <main>
<?php
}

function page_bottom(): void
{
    ?>
    <p><a href="/hw2/">&larr; HW2 index</a> · <a href="/">Home</a></p>
  </main>

  <footer>
    <p>CSE 135 · HW2 · generated by <?= h(LANG_NAME) ?></p>
  </footer>
</body>

</html>
<?php
}

/**
 * Render an associative array as a definition table.
 * Every key and value is escaped — these tables carry user-controlled data.
 *
 * @param array<string,mixed> $rows
 */
function kv_table(array $rows, string $caption): void
{
    echo "    <table class=\"kv\">\n";
    echo '      <caption>' . h($caption) . "</caption>\n";
    echo "      <tbody>\n";
    if ($rows === []) {
        echo "        <tr><td colspan=\"2\"><em>(nothing)</em></td></tr>\n";
    }
    foreach ($rows as $k => $v) {
        if (is_array($v)) {
            $v = json_encode($v, JSON_UNESCAPED_SLASHES);
        }
        echo '        <tr><th scope="row">' . h((string) $k) . '</th><td>'
            . h((string) $v) . "</td></tr>\n";
    }
    echo "      </tbody>\n    </table>\n";
}

/**
 * Emit a JSON response.
 * nosniff matters here: without it a browser can be talked into treating a
 * reflected payload in this body as HTML.
 *
 * @param array<string,mixed> $data
 */
function send_json(array $data): void
{
    header('Content-Type: application/json; charset=utf-8');
    header('X-Content-Type-Options: nosniff');
    header('Cache-Control: no-store');
    echo json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES), "\n";
}
