// Package hw2lib holds the pieces shared by the HW2 Go CGI demos.
//
// Everything here is standard library. The programs are compiled to static
// binaries (CGO_ENABLED=0) in CI and rsynced to the droplet, so the server
// needs no Go toolchain and no shared libraries at runtime.
package hw2lib

import (
	"bytes"
	"encoding/json"
	"html/template"
	"io"
	"net/http"
	"net/url"
	"os"
	"runtime"
	"sort"
	"strings"
	"time"
)

const (
	LangName = "Go"
	TeamName = "Diego — UCSD Wrestling Club"
)

// Pair keeps table rows in insertion order; a map would be reordered.
type Pair struct{ Key, Value string }

// Table is the data for the shared "kv" template.
type Table struct {
	Caption string
	Rows    []Pair
}

// Base carries the fields every page layout needs. Page-specific structs embed
// it, and html/template promotes the fields.
type Base struct {
	Title     string
	Lang      string
	Team      string
	GoVersion string
}

func NewBase(title string) Base {
	return Base{
		Title:     title,
		Lang:      LangName,
		Team:      TeamName,
		GoVersion: runtime.Version(),
	}
}

const head = `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="stylesheet" href="/css/style.css">
  <link rel="stylesheet" href="/hw2/hw2.css">
  <title>{{.Title}}</title>
</head>

<body>
  <header>
    <h1>{{.Title}}</h1>
    <p class="tagline"><span class="lang-badge">{{.Lang}}</span> {{.Team}}</p>
  </header>

  <main>
`

const foot = `    <p><a href="/hw2/">&larr; HW2 index</a> · <a href="/">Home</a></p>
  </main>

  <footer>
    <p>CSE 135 · HW2 · generated by {{.Lang}} {{.GoVersion}}</p>
  </footer>
</body>

</html>
`

const kvTable = `{{define "kv"}}    <table class="kv">
      <caption>{{.Caption}}</caption>
      <tbody>
{{- if not .Rows}}
        <tr><td colspan="2"><em>(nothing)</em></td></tr>
{{- end}}
{{- range .Rows}}
        <tr><th scope="row">{{.Key}}</th><td>{{.Value}}</td></tr>
{{- end}}
      </tbody>
    </table>
{{end}}`

// Render writes a full page. content is a developer-authored template body;
// every value interpolated into it is escaped by html/template, which is what
// keeps the echo demo from reflecting script back at the browser.
func Render(w http.ResponseWriter, content string, data any) {
	tmpl, err := template.New("page").Parse(head + content + foot + kvTable)
	if err != nil {
		http.Error(w, "template error", http.StatusInternalServerError)
		return
	}

	// Render to a buffer first so a mid-render failure cannot emit a half page
	// after the headers have already gone out.
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		http.Error(w, "render error", http.StatusInternalServerError)
		return
	}

	SetCommonHeaders(w, "text/html; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	_, _ = buf.WriteTo(w)
}

func SetCommonHeaders(w http.ResponseWriter, contentType string) {
	h := w.Header()
	h.Set("Content-Type", contentType)
	h.Set("Cache-Control", "no-store")
	// Without nosniff a browser can be talked into treating a reflected
	// payload in a JSON body as HTML.
	h.Set("X-Content-Type-Options", "nosniff")
}

func SendJSON(w http.ResponseWriter, data any) {
	SetCommonHeaders(w, "application/json; charset=utf-8")
	w.WriteHeader(http.StatusOK)
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	_ = enc.Encode(data)
}

// ClientIP is the address Apache reports for the requester.
func ClientIP(r *http.Request) string {
	if ip := os.Getenv("REMOTE_ADDR"); ip != "" {
		return ip
	}
	if r.RemoteAddr != "" {
		return r.RemoteAddr
	}
	return "unknown"
}

func UserAgent(r *http.Request) string {
	if ua := r.Header.Get("User-Agent"); ua != "" {
		return ua
	}
	return "(none sent)"
}

func Hostname(r *http.Request) string {
	if n := os.Getenv("SERVER_NAME"); n != "" {
		return n
	}
	if r.Host != "" {
		return r.Host
	}
	name, _ := os.Hostname()
	return name
}

func NowISO() string {
	return time.Now().Format(time.RFC3339)
}

// ReadBody returns the raw body and the fields parsed out of it, handling both
// x-www-form-urlencoded and application/json.
func ReadBody(r *http.Request) (map[string]any, string) {
	raw, err := io.ReadAll(io.LimitReader(r.Body, 1<<20)) // 1 MiB cap
	if err != nil || len(raw) == 0 {
		return map[string]any{}, ""
	}
	body := string(raw)
	fields := map[string]any{}

	if strings.Contains(strings.ToLower(r.Header.Get("Content-Type")), "application/json") {
		var decoded map[string]any
		if err := json.Unmarshal(raw, &decoded); err == nil {
			return decoded, body
		}
		return fields, body
	}

	values, err := url.ParseQuery(body)
	if err != nil {
		return fields, body
	}
	for k, v := range values {
		if len(v) > 0 {
			fields[k] = v[0]
		}
	}
	return fields, body
}

// SortedPairs renders a map as ordered rows, so output is stable across loads.
func SortedPairs(m map[string]any) []Pair {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	rows := make([]Pair, 0, len(keys))
	for _, k := range keys {
		rows = append(rows, Pair{Key: k, Value: Stringify(m[k])})
	}
	return rows
}

func Stringify(v any) string {
	switch t := v.(type) {
	case nil:
		return ""
	case string:
		return t
	default:
		b, err := json.Marshal(v)
		if err != nil {
			return ""
		}
		return string(b)
	}
}
